import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright-core';

const base = process.env.VERIFY_BASE_URL || 'http://127.0.0.1:5174';
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1916, height: 1000 } });
const errors = [];
const searches = [];
let failSearch = false;
page.on('pageerror', error => errors.push(error.message));
await page.addInitScript(() => sessionStorage.setItem('generalEnquiryShown', 'true'));
const date = '2027-10-09';
const segment = (id, from, to, start, end, minutes, airline = 'IX', terminal = '2') => ({ id, da: { code: from, name: `${from} Airport`, terminal }, aa: { code: to, name: `${to} Airport`, terminal: '1' }, dt: `${date}T${start}`, at: `${date}T${end}`, duration: minutes, stops: 0, fD: { aI: { code: airline, name: airline === 'IX' ? 'AI Express' : 'Akasa Air' }, fN: '1205' } });
const fare = (id, amount) => ({ id, fareIdentifier: 'PUBLISHED', fD: { ADULT: { fC: { TF: amount }, rT: 1, cc: 'ECONOMY', sR: 9, bI: { iB: '15 Kg', cB: '7 Kg' } } } });
const trips = [
  { id: 'connecting', sI: [{ ...segment('s1', 'BLR', 'BOM', '16:20', '18:20', 120), cT: 90 }, segment('s2', 'BOM', 'DEL', '19:50', '21:50', 120)], totalPriceList: [fare('p1', 8567), fare('p2', 9647), fare('p3', 9699), fare('p4', 9900)] },
  { id: 'direct', sI: [segment('s3', 'BLR', 'DEL', '17:20', '19:57', 157, 'QP', '1')], totalPriceList: [fare('p5', 8705)] },
];
await page.route('**/api/**', async route => {
  const url = new URL(route.request().url());
  let data = [];
  if (url.pathname === '/api/flights/search/') {
    searches.push(route.request().postDataJSON());
    if (failSearch) return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Backend server is not running. Start Django.' }) });
    const query = searches.at(-1).searchQuery;
    data = { searchToken: 'fixture-token', searchResult: { tripInfos: { ONWARD: trips, ...(query.routeInfos.length === 2 ? { RETURN: [{ ...trips[1], totalPriceList: [fare('return-1', 8705)] }] } : {}) } } };
  }
  if (url.pathname === '/api/flights/fare-rules/') {
    assert.equal(route.request().postDataJSON().searchToken, 'fixture-token');
    assert.equal(route.request().postDataJSON().priceId, 'p1');
    data = { fareRule: { 'BLR-DEL': { tfr: { CANCELLATION: [{ amount: 500, st: 24, et: 72, policyInfo: 'Cancellation policy fixture' }] }, miscInfo: 'Additional supplier conditions' } } };
  }
  if (url.pathname === '/api/flights/review/') {
    assert.ok(route.request().postDataJSON().priceIds.length > 0);
    assert.equal(route.request().postDataJSON().searchToken, 'fixture-token');
    data = { tripInfos: [trips[0]], conditions: { st: 300 }, totalPriceInfo: { totalFareDetail: { fC: { BF: 7000, TAF: 1700, TF: 8700 } } }, alerts: [{ type: 'FAREALERT' }] };
  }
  await route.fulfill({ contentType: 'application/json', body: JSON.stringify(data) });
});
await mkdir('output/flights', { recursive: true });
try {
  await page.goto(`${base}/flights`, { waitUntil: 'networkidle' });
  await page.locator('.flight-airline-menu summary').click();
  assert.deepEqual((await page.locator('.flight-airline-menu label').allInnerTexts()).map(name => name.trim()), ['IndiGo', 'SpiceJet', 'Air India', 'Akasa Air', 'AI Express', 'Emirates Airlines', 'Etihad Airways', 'Singapore Airlines', 'Qatar Airways', 'Malaysia Airline']);
  await page.locator('.flight-airline-menu summary').click();
  await page.locator('.flight-pax-trigger').click();
  await page.getByRole('button', { name: 'Adult: 2', exact: true }).click();
  await page.getByRole('button', { name: 'Children: 1', exact: true }).click();
  await page.getByRole('radio', { name: 'Business', exact: true }).check();
  assert.equal(await page.getByRole('button', { name: 'Children: 3', exact: true }).isDisabled(), true);
  await page.screenshot({ path: 'output/flights/passenger-picker.png' });
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  assert.match(await page.locator('.flight-pax-trigger').innerText(), /3 Passengers \| Business/);
  await page.locator('.flight-pax-trigger').click();
  await page.getByRole('button', { name: 'Adult: 1', exact: true }).click();
  await page.getByRole('button', { name: 'Children: 0', exact: true }).click();
  await page.getByRole('radio', { name: 'Economy', exact: true }).check();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog', { name: 'Passengers and cabin class' }).count(), 0);
  await page.getByRole('button', { name: 'Student fare eligibility', exact: true }).click();
  assert.match(await page.getByRole('tooltip').innerText(), /valid student ID/);
  await page.screenshot({ path: 'output/flights/student-fare.png' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Senior Citizen fare eligibility', exact: true }).click();
  assert.match(await page.getByRole('tooltip').innerText(), /date of birth/);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'ROUND TRIP', exact: true }).click();
  await page.getByLabel('Return date', { exact: true }).waitFor();
  await page.screenshot({ path: 'output/flights/round-trip.png' });
  await page.getByRole('button', { name: 'MULTI CITY', exact: true }).click();
  await page.getByRole('button', { name: 'ADD ONE MORE' }).click();
  assert.equal(await page.getByRole('combobox', { name: /Journey .* origin/ }).count(), 3);
  await page.screenshot({ path: 'output/flights/multi-city.png' });
  await page.getByRole('button', { name: 'ONE WAY', exact: true }).click();
  await page.getByLabel('Journey 1 origin', { exact: true }).fill('BLR');
  await page.getByLabel('Journey 1 destination', { exact: true }).fill('DEL');
  await page.getByLabel('Journey 1 departure date', { exact: true }).fill(date);
  await page.screenshot({ path: 'output/flights/search.png' });
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.waitForURL('**/flights/results');
  await page.locator('.flight-card').first().waitFor();
  assert.equal(searches[0].searchQuery.routeInfos[0].fromCityOrAirport.code, 'BLR');
  assert.equal(searches[0].searchQuery.routeInfos[0].toCityOrAirport.code, 'DEL');
  assert.equal(searches[0].searchQuery.routeInfos[0].travelDate, date);
  assert.equal(searches[0].searchQuery.cabinClass, 'ECONOMY');
  assert.equal(searches[0].searchQuery.paxInfo.ADULT, 1);
  assert.equal(searches[0].searchQuery.searchModifiers.pfts, 'REGULAR');
  assert.equal(await page.locator('.flight-card').count(), 2);
  await page.screenshot({ path: 'output/flights/results.png' });
  await page.getByRole('button', { name: 'Non Stop', exact: true }).click();
  assert.equal(await page.locator('.flight-card').count(), 1);
  assert.match(await page.locator('.flight-card').innerText(), /Akasa Air/);
  await page.getByRole('button', { name: 'RESET ALL' }).click();
  await page.getByLabel('Flight number', { exact: true }).fill('QP-1205');
  assert.equal(await page.locator('.flight-card').count(), 1);
  await page.getByRole('button', { name: 'RESET ALL' }).click();
  await page.getByText('Layover Airport', { exact: true }).click();
  await page.getByLabel('BOM', { exact: true }).check();
  assert.equal(await page.locator('.flight-card').count(), 1);
  await page.getByRole('button', { name: 'RESET ALL' }).click();
  await page.getByRole('button', { name: 'View Details +' }).first().click();
  await page.locator('.flight-segments').waitFor();
  await page.getByRole('button', { name: 'View fare rules', exact: true }).click();
  await page.getByText('Cancellation policy fixture', { exact: true }).waitFor();
  await page.getByText('Additional supplier conditions', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Compare', exact: true }).first().click();
  await page.getByRole('button', { name: 'Compare flights', exact: true }).click();
  await page.getByRole('dialog', { name: 'Compare flights' }).waitFor();
  await page.getByRole('button', { name: 'Close comparison' }).click();
  await page.getByRole('button', { name: 'BOOK', exact: true }).first().click();
  await page.waitForURL('**/flights/review');
  assert.equal(await page.getByRole('button', { name: 'Continue to travel team' }).isDisabled(), true);
  await page.getByLabel('I accept the updated fare.').check();
  await page.getByRole('link', { name: 'Continue to travel team' }).waitFor();
  await page.screenshot({ path: 'output/flights/review.png' });
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('heading', { name: 'Check your flight details' }).waitFor();
  await page.getByRole('link', { name: 'Back to results', exact: true }).click();
  await page.getByRole('button', { name: 'Next week', exact: true }).click();
  await page.locator('.flight-card').first().waitFor();
  assert.equal(searches.at(-1).searchQuery.routeInfos[0].travelDate, '2027-10-16');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'output/flights/results-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  await page.getByRole('button', { name: 'Show filters' }).click();
  await page.getByRole('button', { name: 'Non Stop', exact: true }).click();
  assert.equal(await page.locator('.flight-card').count(), 1);
  await page.getByRole('button', { name: 'MODIFY SEARCH' }).click();
  await page.locator('.flight-pax-trigger').click();
  await page.screenshot({ path: 'output/flights/passenger-picker-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByRole('button', { name: 'ROUND TRIP', exact: true }).click();
  await page.getByLabel('Return date', { exact: true }).fill('2027-10-20');
  await page.screenshot({ path: 'output/flights/search-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.locator('.flight-card').first().waitFor();
  await page.getByRole('button', { name: 'SELECT', exact: true }).first().click();
  await page.getByRole('button', { name: 'SELECT', exact: true }).first().click();
  await page.waitForURL('**/flights/review');
  await page.goto(`${base}/flights`);
  await page.getByRole('button', { name: 'ONE WAY', exact: true }).click();
  failSearch = true;
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(), /Backend server is not running/);
  assert.deepEqual(errors, []);
  console.log('Passed: journey tabs, routing, date changes, filters, compare, fare-alert acceptance, review reload, round-trip selections, mobile overflow and backend error display. Supplier APIs mocked.');
} finally { await browser.close(); }
